//! Replays the committed golden vectors through the shipped code.
//!
//! The vectors live at `docs/audits/2026-09-protected-content-golden-vectors-v1.json`
//! and are regenerated by `examples/golden_vectors.rs`. Nothing here
//! re-implements a primitive: each assertion runs this crate's public API, or
//! the exact dependency version this crate links against, and compares the
//! result with the recorded bytes. A suite change that moves any of these
//! bytes fails here rather than silently shipping.

use std::path::PathBuf;

use elastos_protected_content_contracts::{
    CanonicalContract, Digest32, ProfileIdentityV1, RuntimeSessionBindingV1,
    PQ_HYBRID_WRAP_PUBLIC_KEY_BYTES, X_WING_DRAFT06_CIPHERTEXT_BYTES,
};
use elastos_protected_content_custody::{
    answer_recipient_possession_challenge, framed_chunk_ranges_v1,
    issue_recipient_possession_challenge, mint_decrypt_session_from_seed, possession_transcript_v1,
    RecipientSecretKeyV1, PAYLOAD_PLAINTEXT_CHUNK_BYTES_V1, SUITE_PQ_HYBRID,
};
use hkdf::Hkdf;
use rand09::{rngs::StdRng as HpkeStdRng, SeedableRng as _};
use rand10::{rngs::StdRng as ShamirStdRng, SeedableRng as _};
use serde_json::Value;
use sha2::Sha256;
use vsss_rs::Gf256;
use x_wing::kem::{Decapsulate as _, Decapsulator as _, KeyExport as _};
use zeroize::Zeroizing;

const SCHEMA_V1: &str = "elastos.protected-content.golden-vectors/v1";
const OUTPUT_RELATIVE_PATH: &str = "docs/audits/2026-09-protected-content-golden-vectors-v1.json";

fn document() -> Value {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let repo_root = manifest
        .ancestors()
        .nth(3)
        .expect("crate lives at <repo>/elastos/crates/<crate>");
    let path = repo_root.join(OUTPUT_RELATIVE_PATH);
    let bytes = std::fs::read(&path).unwrap_or_else(|error| {
        panic!(
            "golden vector file {} must exist (regenerate with `cargo run -p \
             elastos-protected-content-custody --example golden_vectors`): {error}",
            path.display()
        )
    });
    serde_json::from_slice(&bytes).expect("golden vector file must be valid JSON")
}

fn family(name: &str) -> Vec<Value> {
    document()["vectors"][name]
        .as_array()
        .unwrap_or_else(|| panic!("golden vector family `{name}` must be a JSON array"))
        .clone()
}

fn bytes(entry: &Value, field: &str) -> Vec<u8> {
    let encoded = entry[field]
        .as_str()
        .unwrap_or_else(|| panic!("field `{field}` must be a hex string"));
    hex::decode(encoded).unwrap_or_else(|error| panic!("field `{field}` must be hex: {error}"))
}

fn seed32(entry: &Value, field: &str) -> [u8; 32] {
    bytes(entry, field)
        .try_into()
        .unwrap_or_else(|_| panic!("field `{field}` must be 32 bytes"))
}

/// The schema string is the contract with whoever consumes this file. Changing
/// it is a deliberate, breaking act, so it fails here first.
#[test]
fn golden_vector_schema_and_suite_are_unchanged() {
    let document = document();
    assert_eq!(
        document["schema"].as_str(),
        Some(SCHEMA_V1),
        "golden vector schema string changed"
    );
    assert_eq!(
        document["suite_id"].as_str(),
        Some(SUITE_PQ_HYBRID),
        "recorded suite id no longer matches the shipped suite id"
    );
    for name in [
        "decrypt_session_keygen",
        "eip191_recover",
        "epc1_framed_chunk_ranges",
        "hkdf_sha256_no_salt",
        "possession_challenge_seal",
        "recipient_key_identity",
        "shamir_gf256_2_of_3",
        "xwing_decaps",
    ] {
        assert!(
            !family(name).is_empty(),
            "golden vector family `{name}` must carry at least one vector"
        );
    }
}

#[test]
fn xwing_decapsulation_matches_recorded_shared_secrets() {
    for entry in family("xwing_decaps") {
        let decapsulation_key = x_wing::DecapsulationKey::from(seed32(&entry, "dk"));
        let ciphertext: [u8; X_WING_DRAFT06_CIPHERTEXT_BYTES] = bytes(&entry, "ct")
            .try_into()
            .expect("recorded ciphertext must be the X-Wing draft-06 length");
        let shared_secret = decapsulation_key
            .decapsulate_slice(&ciphertext)
            .expect("recorded ciphertext must decapsulate");
        assert_eq!(shared_secret.as_slice(), bytes(&entry, "ss"));

        let encapsulation_key: [u8; PQ_HYBRID_WRAP_PUBLIC_KEY_BYTES] =
            Into::into(decapsulation_key.encapsulation_key().to_bytes());
        assert_eq!(encapsulation_key.as_slice(), bytes(&entry, "ek"));
    }
}

#[test]
fn hkdf_sha256_no_salt_matches_recorded_output() {
    for entry in family("hkdf_sha256_no_salt") {
        let expected = bytes(&entry, "okm");
        let mut okm = vec![0u8; expected.len()];
        Hkdf::<Sha256>::new(None, &bytes(&entry, "ikm"))
            .expand(&bytes(&entry, "info"), &mut okm)
            .expect("hkdf expand");
        assert_eq!(okm, expected);
    }
}

#[test]
fn shamir_gf256_2_of_3_splits_and_recombines_as_recorded() {
    for entry in family("shamir_gf256_2_of_3") {
        let secret = bytes(&entry, "secret");
        let recorded: Vec<Vec<u8>> = entry["shares"]
            .as_array()
            .expect("shares must be an array")
            .iter()
            .map(|share| hex::decode(share.as_str().expect("share must be hex")).expect("hex"))
            .collect();

        let mut rng = ShamirStdRng::from_seed(seed32(&entry, "rng_seed"));
        let mut produced: Vec<Vec<u8>> =
            Gf256::split_bytes(2, 3, &secret, &mut rng).expect("shamir split");
        produced.sort_by_key(|share| share[0]);
        assert_eq!(
            produced, recorded,
            "recorded Shamir shares are not reproduced"
        );

        for pair in entry["reconstructed_from"]
            .as_array()
            .expect("reconstructed_from must be an array")
        {
            let indexes: Vec<usize> = pair
                .as_array()
                .expect("share pair must be an array")
                .iter()
                .map(|index| index.as_u64().expect("share index") as usize)
                .collect();
            let subset: Vec<Vec<u8>> = indexes
                .iter()
                .map(|index| recorded[*index].clone())
                .collect();
            assert_eq!(
                Gf256::combine_bytes(&subset).expect("shamir combine"),
                secret,
                "2-of-3 reconstruction failed for share pair {indexes:?}"
            );
        }

        // One share must not be enough: recombining a single share cannot
        // return the secret.
        for share in &recorded {
            let single = vec![share.clone()];
            if let Ok(value) = Gf256::combine_bytes(&single) {
                assert_ne!(value, secret, "one share reconstructed the secret");
            }
        }
    }
}

#[test]
fn eip191_recovery_matches_recorded_addresses_and_rejects_high_s() {
    use k256::ecdsa::{RecoveryId, Signature, VerifyingKey};
    use sha3::{Digest as _, Keccak256};

    for entry in family("eip191_recover") {
        let message = entry["message"].as_str().expect("message must be a string");
        let hash = elastos_auth::ethereum_signed_message_hash(message.as_bytes());
        assert_eq!(hash.as_slice(), bytes(&entry, "prefixed_hash"));

        let signature_bytes = bytes(&entry, "signature");
        assert_eq!(signature_bytes.len(), 65, "signature must be 65 bytes");
        let signature = Signature::from_slice(&signature_bytes[..64]).expect("signature");
        assert!(
            signature.normalize_s().is_none(),
            "recorded signature must already be low-S, as the rights contract requires"
        );
        let recovery_id = RecoveryId::from_byte(signature_bytes[64]).expect("recovery id");
        let verifying_key =
            VerifyingKey::recover_from_prehash(&hash, &signature, recovery_id).expect("recover");
        let encoded = verifying_key.to_encoded_point(false);
        let address = format!(
            "0x{}",
            hex::encode(&Keccak256::digest(&encoded.as_bytes()[1..])[12..])
        );
        assert_eq!(Some(address.as_str()), entry["address"].as_str());
    }
}

#[test]
fn decrypt_session_keygen_matches_recorded_public_keys() {
    for entry in family("decrypt_session_keygen") {
        let (_secret, public) =
            mint_decrypt_session_from_seed(seed32(&entry, "seed")).expect("decrypt session");
        assert_eq!(public.as_bytes().as_slice(), bytes(&entry, "public_key"));
    }
}

#[test]
fn recipient_key_identity_matches_recorded_binding() {
    for entry in family("recipient_key_identity") {
        let secret =
            RecipientSecretKeyV1::from_guarded_bytes(Zeroizing::new(seed32(&entry, "seed")))
                .expect("recipient key");
        let public = secret.public_key().expect("recipient public key");
        let identity = secret.identity().expect("recipient identity");
        assert_eq!(public.as_bytes().as_slice(), bytes(&entry, "public_key"));
        assert_eq!(
            Some(identity.encryption_suite_id()),
            entry["encryption_suite_id"].as_str()
        );
        assert_eq!(
            identity.key_id().as_bytes().as_slice(),
            bytes(&entry, "key_id")
        );
        assert_eq!(
            identity.canonical_bytes().expect("canonical identity"),
            bytes(&entry, "canonical_bytes")
        );
    }
}

#[test]
fn possession_challenge_seal_reproduces_recorded_envelope_and_opens() {
    for entry in family("possession_challenge_seal") {
        let recipient_seed = seed32(&entry, "recipient_seed");
        let secret = RecipientSecretKeyV1::from_guarded_bytes(Zeroizing::new(recipient_seed))
            .expect("recipient key");
        let public = secret.public_key().expect("recipient public key");
        let identity = secret.identity().expect("recipient identity");

        let profile_public: [u8; 32] = bytes(&entry, "profile_public_key")
            .try_into()
            .expect("profile public key must be 32 bytes");
        let profile =
            ProfileIdentityV1::from_public_key_bytes(profile_public).expect("profile identity");
        let session =
            RuntimeSessionBindingV1::new(Digest32::new(seed32(&entry, "runtime_session_binding")))
                .expect("runtime session binding");
        let request_hash = Digest32::new(seed32(&entry, "request_hash"));

        let transcript = possession_transcript_v1(profile, session, &identity, request_hash)
            .expect("possession transcript");
        assert_eq!(
            transcript,
            bytes(&entry, "transcript"),
            "session-binding transcript preimage changed"
        );

        let challenge = issue_recipient_possession_challenge(
            &public,
            &transcript,
            &mut HpkeStdRng::from_seed(seed32(&entry, "rng_seed")),
        )
        .expect("possession challenge");
        assert_eq!(
            challenge
                .sealed_share()
                .canonical_bytes()
                .expect("canonical sealed share"),
            bytes(&entry, "sealed_share"),
            "X-Wing / HKDF-SHA256 / AES-256-GCM seal no longer reproduces the recorded envelope"
        );

        let verified = answer_recipient_possession_challenge(
            &secret,
            &public,
            &identity,
            &challenge,
            &transcript,
        )
        .expect("recorded challenge must open under the recorded recipient secret");
        assert_eq!(verified.identity(), &identity);

        // Fail-closed: the same envelope under a different transcript must not
        // open, which is what binds a challenge to one session.
        let mut wrong_transcript = transcript.clone();
        wrong_transcript.push(0xff);
        assert!(
            answer_recipient_possession_challenge(
                &secret,
                &public,
                &identity,
                &challenge,
                &wrong_transcript,
            )
            .is_err(),
            "a challenge opened under a transcript it was not sealed to"
        );
    }
}

#[test]
fn epc1_framed_chunk_ranges_match_recorded_framing() {
    for entry in family("epc1_framed_chunk_ranges") {
        assert_eq!(
            entry["plaintext_chunk_bytes"].as_u64(),
            Some(u64::from(PAYLOAD_PLAINTEXT_CHUNK_BYTES_V1)),
            "EPC1 plaintext chunk size changed"
        );
        let framed_header_bytes = entry["framed_header_bytes"]
            .as_u64()
            .expect("framed_header_bytes") as u32;
        let plaintext_bytes = entry["plaintext_bytes"].as_u64().expect("plaintext_bytes");
        let produced: Vec<[u64; 2]> = framed_chunk_ranges_v1(framed_header_bytes, plaintext_bytes)
            .map(|range| [range.start, range.end])
            .collect();
        let recorded: Vec<[u64; 2]> = entry["ranges"]
            .as_array()
            .expect("ranges must be an array")
            .iter()
            .map(|range| {
                let pair = range.as_array().expect("range must be a pair");
                [
                    pair[0].as_u64().expect("range start"),
                    pair[1].as_u64().expect("range end"),
                ]
            })
            .collect();
        assert_eq!(produced, recorded, "EPC1 framed chunk ranges changed");
    }
}
