//! Golden-vector generator for the protected-content cryptographic suite.
//!
//! Regenerate with:
//!
//! ```text
//! cargo run -p elastos-protected-content-custody --example golden_vectors
//! ```
//!
//! It rewrites `docs/audits/2026-09-protected-content-golden-vectors-v1.json`
//! in place. `tests/golden_vectors.rs` replays the committed file and fails if
//! any shipped code path stops reproducing it.
//!
//! Every vector is produced by calling the code that actually ships: either
//! this crate's own public API, or the exact dependency version this crate
//! links against (`x-wing`, `hkdf`, `vsss-rs`, `k256`, `elastos-auth`). No
//! primitive is re-implemented here — a vector generated by a second
//! implementation would only ever test that second implementation.
//!
//! Deliberate gap: there is no keyed `EPC1` chunk vector. Producing one needs
//! a `ContentEncryptionKeyV1` with known bytes, and this crate does not expose
//! raw content-key bytes across its public API by design. The EPC1 framing is
//! pinned here structurally (`epc1_framed_chunk_ranges`) and keyed behaviour
//! is pinned by the crate's in-module tests. See
//! `docs/PROTECTED_CONTENT_CRYPTO_REVIEW.md`.

use std::path::PathBuf;

use elastos_protected_content_contracts::{
    CanonicalContract, Digest32, ProfileIdentityV1, RuntimeSessionBindingV1,
    PQ_HYBRID_WRAP_PUBLIC_KEY_BYTES, X_WING_DRAFT06_CIPHERTEXT_BYTES,
};
use elastos_protected_content_custody::{
    framed_chunk_ranges_v1, issue_recipient_possession_challenge, mint_decrypt_session_from_seed,
    possession_transcript_v1, RecipientSecretKeyV1, PAYLOAD_PLAINTEXT_CHUNK_BYTES_V1,
    SUITE_PQ_HYBRID,
};
use hkdf::Hkdf;
use rand09::{rngs::StdRng as HpkeStdRng, SeedableRng as _};
use rand10::{rngs::StdRng as ShamirStdRng, SeedableRng as _};
use serde_json::{json, Map, Value};
use sha2::Sha256;
use vsss_rs::Gf256;
use x_wing::kem::{Decapsulate as _, Decapsulator as _, KeyExport as _};
use zeroize::Zeroizing;

const SCHEMA_V1: &str = "elastos.protected-content.golden-vectors/v1";
const OUTPUT_RELATIVE_PATH: &str = "docs/audits/2026-09-protected-content-golden-vectors-v1.json";

fn main() {
    let document = build_document();
    let path = output_path();
    let mut rendered = serde_json::to_string_pretty(&document).expect("vectors must serialize");
    rendered.push('\n');
    std::fs::create_dir_all(path.parent().expect("output path has a parent"))
        .expect("audit directory must be creatable");
    std::fs::write(&path, rendered).expect("golden vector file must be writable");
    println!("{}", path.display());
}

/// `<repo>/docs/audits/...`, resolved from this crate's manifest directory so
/// the example works from any current directory.
fn output_path() -> PathBuf {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let repo_root = manifest
        .ancestors()
        .nth(3)
        .expect("crate lives at <repo>/elastos/crates/<crate>")
        .to_path_buf();
    repo_root.join(OUTPUT_RELATIVE_PATH)
}

fn build_document() -> Value {
    let mut vectors = Map::new();
    vectors.insert("decrypt_session_keygen".into(), decrypt_session_keygen());
    vectors.insert("eip191_recover".into(), eip191_recover());
    vectors.insert(
        "epc1_framed_chunk_ranges".into(),
        epc1_framed_chunk_ranges(),
    );
    vectors.insert("hkdf_sha256_no_salt".into(), hkdf_sha256_no_salt());
    vectors.insert(
        "possession_challenge_seal".into(),
        possession_challenge_seal(),
    );
    vectors.insert("recipient_key_identity".into(), recipient_key_identity());
    vectors.insert("shamir_gf256_2_of_3".into(), shamir_gf256_2_of_3());
    vectors.insert("xwing_decaps".into(), xwing_decaps());

    json!({
        "schema": SCHEMA_V1,
        "generated_by": concat!(env!("CARGO_PKG_NAME"), " ", env!("CARGO_PKG_VERSION")),
        "suite_id": SUITE_PQ_HYBRID,
        "vectors": Value::Object(vectors),
    })
}

/// X-Wing draft-06 decapsulation, from the `x-wing` version this crate links.
/// `dk` is the 32-byte seed the decapsulation key is expanded from, which is
/// exactly the representation this crate stores and imports
/// (`session_secret_from_bytes`). Recording `ct` and `ss` from one
/// deterministic encapsulation means the replay only has to decapsulate.
fn xwing_decaps() -> Value {
    let mut entries = Vec::new();
    for (dk_seed_byte, randomness_byte) in [(0x4du8, 0x11u8), (0xa3, 0xc7)] {
        let dk_seed = [dk_seed_byte; 32];
        let randomness = [randomness_byte; x_wing::ENCAPSULATION_RANDOMNESS_SIZE];
        let dk = x_wing::DecapsulationKey::from(dk_seed);
        let ek = dk.encapsulation_key().clone();
        let (ct, ss) = ek.encapsulate_deterministic(&randomness.into());
        let ct_bytes = Into::<[u8; X_WING_DRAFT06_CIPHERTEXT_BYTES]>::into(ct);
        let decapsulated = dk.decapsulate_slice(&ct_bytes).expect("decapsulate");
        assert_eq!(
            decapsulated.as_slice(),
            ss.as_slice(),
            "recorded shared secret must be what decapsulation returns"
        );
        let ek_bytes = Into::<[u8; PQ_HYBRID_WRAP_PUBLIC_KEY_BYTES]>::into(ek.to_bytes());
        entries.push(json!({
            "dk": hex::encode(dk_seed),
            "ek": hex::encode(ek_bytes),
            "encapsulation_randomness": hex::encode(randomness),
            "ct": hex::encode(ct_bytes),
            "ss": hex::encode(ss.as_slice()),
        }));
    }
    Value::Array(entries)
}

/// HKDF-SHA256 with **no salt**, the mode this crate's wrap-key derivation
/// uses (`Hkdf::<Sha256>::new(None, shared_secret)`). Entry 0 is RFC 5869
/// test case A.3, so an external reviewer can check the primitive against the
/// published vector without trusting this repository. The *info* string this
/// crate actually builds is not reproduced here — it is pinned byte-for-byte
/// by `possession_challenge_seal`.
fn hkdf_sha256_no_salt() -> Value {
    let cases: [(&str, Vec<u8>, Vec<u8>, usize); 2] = [
        ("RFC 5869 A.3", vec![0x0b; 22], Vec::new(), 42),
        (
            "X-Wing shared-secret sized input, 32-byte output",
            vec![0x5a; 32],
            b"elastos.protected-content.golden-vector.hkdf/v1".to_vec(),
            32,
        ),
    ];
    let mut entries = Vec::new();
    for (source, ikm, info, length) in cases {
        let mut okm = vec![0u8; length];
        Hkdf::<Sha256>::new(None, &ikm)
            .expand(&info, &mut okm)
            .expect("hkdf expand");
        entries.push(json!({
            "source": source,
            "ikm": hex::encode(&ikm),
            "info": hex::encode(&info),
            "okm": hex::encode(&okm),
        }));
    }
    Value::Array(entries)
}

/// `vsss-rs` `Gf256` Shamir sharing over GF(256), 2-of-3, exactly as
/// `provision.rs` calls it. Shares are recorded in the crate's own wire shape:
/// a one-byte share coordinate followed by the 32-byte share value.
fn shamir_gf256_2_of_3() -> Value {
    let mut entries = Vec::new();
    for (secret_byte, rng_seed_byte) in [(0x33u8, 0x42u8), (0xf0, 0x07)] {
        let secret = [secret_byte; 32];
        let rng_seed = [rng_seed_byte; 32];
        let mut rng = ShamirStdRng::from_seed(rng_seed);
        let mut shares: Vec<Vec<u8>> =
            Gf256::split_bytes(2, 3, secret, &mut rng).expect("shamir split");
        shares.sort_by_key(|share| share[0]);
        entries.push(json!({
            "secret": hex::encode(secret),
            "rng": "rand 0.10 StdRng::from_seed",
            "rng_seed": hex::encode(rng_seed),
            "required": 2,
            "total": 3,
            "shares": shares.iter().map(hex::encode).collect::<Vec<_>>(),
            "reconstructed_from": [[0, 1], [0, 2], [1, 2]],
        }));
    }
    Value::Array(entries)
}

/// EIP-191 personal-sign recovery with the low-S rejection the rights
/// contract enforces (`rights.rs`'s `recover_wallet`). The prefixed hash comes
/// from `elastos_auth::ethereum_signed_message_hash`; recovery and address
/// derivation use the same `k256` and Keccak-256 this workspace links. The
/// trailing recovery byte is the raw 0/1 form the contract parses, not 27/28.
fn eip191_recover() -> Value {
    use k256::ecdsa::SigningKey;
    use sha3::{Digest as _, Keccak256};

    let mut entries = Vec::new();
    for (seed_byte, message) in [(0x21u8, "elastos golden vector message"), (0x9cu8, "")] {
        let signing_key = SigningKey::from_bytes(&[seed_byte; 32].into()).expect("signing key");
        let hash = elastos_auth::ethereum_signed_message_hash(message.as_bytes());
        let (signature, recovery_id) = signing_key
            .sign_prehash_recoverable(&hash)
            .expect("recoverable signature");
        let mut signature_bytes = signature.to_bytes().to_vec();
        signature_bytes.push(recovery_id.to_byte());

        let encoded = signing_key
            .verifying_key()
            .to_encoded_point(false)
            .as_bytes()
            .to_vec();
        let address = &Keccak256::digest(&encoded[1..])[12..];
        entries.push(json!({
            "message": message,
            "prefixed_hash": hex::encode(hash),
            "signature": hex::encode(&signature_bytes),
            "address": format!("0x{}", hex::encode(address)),
        }));
    }
    Value::Array(entries)
}

/// `mint_decrypt_session_from_seed`: SHA-256 over a fixed label and the seed,
/// then an X-Wing decapsulation key from that. Pins the whole derivation
/// through this crate's public API — only the resulting public key is
/// recorded, never the derived secret.
fn decrypt_session_keygen() -> Value {
    let mut entries = Vec::new();
    for seed_byte in [0x51u8, 0xbe] {
        let seed = [seed_byte; 32];
        let (_secret, public) = mint_decrypt_session_from_seed(seed).expect("decrypt session");
        entries.push(json!({
            "seed": hex::encode(seed),
            "public_key": hex::encode(public.as_bytes()),
        }));
    }
    Value::Array(entries)
}

/// `RecipientSecretKeyV1` public key and the `RecipientKeyIdentityV1` it
/// binds to: suite id plus SHA-256 over the 1216-byte X-Wing public key,
/// canonically encoded. This is the identity an authorization names, so it is
/// the value a release is checked against.
fn recipient_key_identity() -> Value {
    let mut entries = Vec::new();
    for seed_byte in [0x30u8, 0x42] {
        let seed = [seed_byte; 32];
        let secret =
            RecipientSecretKeyV1::from_guarded_bytes(Zeroizing::new(seed)).expect("recipient key");
        let public = secret.public_key().expect("recipient public key");
        let identity = secret.identity().expect("recipient identity");
        entries.push(json!({
            "seed": hex::encode(seed),
            "public_key": hex::encode(public.as_bytes()),
            "encryption_suite_id": identity.encryption_suite_id(),
            "key_id": hex::encode(identity.key_id().as_bytes()),
            "canonical_bytes": hex::encode(
                identity.canonical_bytes().expect("canonical identity"),
            ),
        }));
    }
    Value::Array(entries)
}

/// The one end-to-end vector: recipient-possession challenge issuance, which
/// runs X-Wing encapsulation, this crate's HKDF-SHA256 wrap-key derivation
/// (including its exact domain-separated `info`), and AES-256-GCM over the
/// bound AAD — all through the public API, byte for byte, under a seeded RNG.
/// Any change to the transcript layout, the HKDF info encoding, the AAD
/// binding, or the envelope framing moves these bytes.
fn possession_challenge_seal() -> Value {
    let mut entries = Vec::new();
    for (recipient_seed_byte, profile_seed_byte, rng_seed_byte, session_byte, request_byte) in [
        (0x30u8, 0x11u8, 0x61u8, 0x66u8, 0x77u8),
        (0x42, 0x8a, 0xd4, 0x2b, 0xe9),
    ] {
        let recipient_seed = [recipient_seed_byte; 32];
        let secret = RecipientSecretKeyV1::from_guarded_bytes(Zeroizing::new(recipient_seed))
            .expect("recipient key");
        let public = secret.public_key().expect("recipient public key");
        let identity = secret.identity().expect("recipient identity");

        let profile_seed = [profile_seed_byte; 32];
        let profile_public = ed25519_dalek::SigningKey::from_bytes(&profile_seed)
            .verifying_key()
            .to_bytes();
        let profile =
            ProfileIdentityV1::from_public_key_bytes(profile_public).expect("profile identity");
        let session_digest = [session_byte; 32];
        let session = RuntimeSessionBindingV1::new(Digest32::new(session_digest))
            .expect("runtime session binding");
        let request_hash = Digest32::new([request_byte; 32]);

        let transcript = possession_transcript_v1(profile, session, &identity, request_hash)
            .expect("possession transcript");
        let rng_seed = [rng_seed_byte; 32];
        let challenge = issue_recipient_possession_challenge(
            &public,
            &transcript,
            &mut HpkeStdRng::from_seed(rng_seed),
        )
        .expect("possession challenge");

        entries.push(json!({
            "recipient_seed": hex::encode(recipient_seed),
            "profile_seed": hex::encode(profile_seed),
            "profile_public_key": hex::encode(profile_public),
            "runtime_session_binding": hex::encode(session_digest),
            "request_hash": hex::encode(request_hash.as_bytes()),
            "transcript": hex::encode(&transcript),
            "rng": "rand 0.9 StdRng::from_seed",
            "rng_seed": hex::encode(rng_seed),
            "sealed_share": hex::encode(
                challenge
                    .sealed_share()
                    .canonical_bytes()
                    .expect("canonical sealed share"),
            ),
        }));
    }
    Value::Array(entries)
}

/// EPC1 object framing: where each sealed chunk starts and ends, given the
/// framed header length and the plaintext size. Pins the 1 MiB plaintext chunk
/// size and the 16-byte AEAD tag per chunk without needing any key material.
fn epc1_framed_chunk_ranges() -> Value {
    let chunk = u64::from(PAYLOAD_PLAINTEXT_CHUNK_BYTES_V1);
    let mut entries = Vec::new();
    for (framed_header_bytes, plaintext_bytes) in [
        (128u32, 0u64),
        (128, 1),
        (128, chunk),
        (128, chunk + 1),
        (211, 3 * chunk + 7),
    ] {
        let ranges: Vec<Value> = framed_chunk_ranges_v1(framed_header_bytes, plaintext_bytes)
            .map(|range| json!([range.start, range.end]))
            .collect();
        entries.push(json!({
            "framed_header_bytes": framed_header_bytes,
            "plaintext_bytes": plaintext_bytes,
            "plaintext_chunk_bytes": PAYLOAD_PLAINTEXT_CHUNK_BYTES_V1,
            "ranges": Value::Array(ranges),
        }));
    }
    Value::Array(entries)
}
