[package]
name = "gba-emulator"
version = "0.1.0"
edition = "2021"
description = "GBA emulator capsule"
license = "MIT"

[[bin]]
name = "gba-emulator"
path = "wasm/main.rs"

[dependencies]
elastos-guest = { path = "../../elastos/crates/elastos-guest" }

[profile.release]
opt-level = "s"
lto = true

[workspace]
